In [1]:
height = [1.2, 1.68, 1.71, 1.89, 1.79]

In [2]:
height

[1.2, 1.68, 1.71, 1.89, 1.79]

In [3]:
weight = [65.4, 59.2, 63.6, 88.4,68.7]

In [4]:
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [5]:
weight/height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [4]:
import numpy as np

In [7]:
np_height = np.array(height)

In [8]:
np_weight = np.array(weight)

In [9]:
np_weight/np_height ** 2

array([ 45.41666667,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

In [10]:
np.random.seed(0) # seed for reproducibility

In [9]:
x1 = np.random.randint(10, size=6) # One dimentional array

In [12]:
x2 = np.random.randint(10, size=(3,4)) # Two dimentional array

In [20]:
x3 = np.random.randint(10, size=(3,4,5)) # Three Dimentional array

In [10]:
x1

array([1, 0, 6, 3, 9, 9])

In [13]:
x2

array([[2, 5, 1, 2],
       [1, 1, 7, 2],
       [6, 7, 2, 3]])

In [21]:
x3

array([[[0, 5, 5, 1, 4],
        [1, 5, 1, 1, 7],
        [5, 7, 9, 1, 6],
        [0, 5, 2, 7, 2]],

       [[0, 1, 2, 1, 3],
        [1, 2, 7, 4, 5],
        [0, 3, 9, 6, 3],
        [9, 7, 5, 4, 8]],

       [[9, 4, 7, 8, 3],
        [6, 6, 9, 2, 2],
        [4, 3, 0, 1, 9],
        [3, 8, 1, 4, 5]]])

In [22]:
print("x2 ndim : ", x2.ndim)
print("x3 ndim : ", x3.ndim)
print("x3 shape : ", x3.shape)
print("x3 size : ", x3.size)

x2 ndim :  2
x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [23]:
print("x3 Data Type : ", x3.dtype)

x3 Data Type :  int64


In [24]:
print("x3 itemsize: ", x3.itemsize, "bytes")

x3 itemsize:  8 bytes


Values Can also be modified using any of the above index notation

In [25]:
x2[0,0] = 12

In [26]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [27]:
x2[1,2] = 15

In [28]:
x2

array([[12,  5,  2,  4],
       [ 7,  6, 15,  8],
       [ 1,  6,  7,  7]])

Array Slicing 

In [29]:
x = np.arange(10)
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [30]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [31]:
x[4:7] # middle sub-array

array([4, 5, 6])

In [32]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [33]:
x[1::2] # every other elements, starting at index 1

array([1, 3, 5, 7, 9])

In [35]:
x2 = np.random.randint(10, size=(3,4)) # two dimentional array
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [36]:
x2[:,1:3]

array([[3, 4],
       [4, 3],
       [5, 0]])

In [37]:
x2[0:2, :2] # two rows, two columns

array([[4, 3],
       [8, 4]])

In [38]:
x2[:3, ::2] # all rows, every other column

array([[4, 4],
       [8, 3],
       [5, 0]])

In [39]:
x2[::-1, ::-1] # reverse all rows and columns

array([[1, 0, 5, 5],
       [7, 3, 4, 8],
       [4, 4, 3, 4]])

In [45]:
print(x2)
x2[:,0] # first column of x2

[[4 3 4 4]
 [8 4 3 7]
 [5 5 0 1]]


array([4, 8, 5])

In [44]:
x2[0, :] # first row of x2

array([4, 3, 4, 4])

Reshaping the Array

In [49]:
grid = np.arange(1,10).reshape((3,3))

In [50]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Concatenating

In [53]:
x = np.array([1,2,3,4])
y = np.array([7,8,9,10])
np.concatenate([x,y])

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [54]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [56]:
x = [1,2,99, 101,102,4,5,201,6,7]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[ 1  2 99] [101 102] [  4   5 201   6   7]
